# Thi workflow will install Python dependencies, run tests and lint with a single version of Python

name: examples

on:
  push:
    paths:
      - "examples/**.py"
jobs:
  cpu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[all]
      - name: Run examples
        run: |
          ./tests/test_examples.sh examples/
