on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

name: Windows build
jobs:
    test-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install miniconda
              uses: conda-incubator/setup-miniconda@v2
              with:
                  auto-activate-base: true
                  python-version: "3.7"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install --user --no-cache-dir Cython
                  pip install --user -r requirements.txt
                  pip install --user -r requirements_dev.txt
                  pip install .
